import { VerticalBox, ListView } from "std-widgets.slint";
import { SourceInfo } from "../components/types.slint";
import { SourceRow } from "../components/source_row.slint";

export component SourcesPage inherits Rectangle {
    in property <[SourceInfo]> source_model;
    in property <bool> operation_busy;

    callback backup_source(int);
    callback toggle_source_expanded(int);

    VerticalBox {
        padding: 12px;
        spacing: 8px;

        ListView {
            vertical-stretch: 1;
            for source[idx] in root.source_model: SourceRow {
                source: source;
                operation_busy: root.operation_busy;
                backup_label: "Backup to all Repos";
                toggle_expanded => { root.toggle_source_expanded(idx); }
                backup_clicked => { root.backup_source(idx); }
            }
        }
    }
}
