import { MainWindow, RepoInfo, SourceInfo } from "main-window.slint";
import { RestoreWindow, TreeRowData } from "restore.slint";
import { PasswordDialog } from "password-dialog.slint";

export { MainWindow, RestoreWindow, PasswordDialog, RepoInfo, SourceInfo, TreeRowData }

export global AppData {
    // Label caches — written by event consumer, read by MainWindow callbacks.
    in-out property <[string]> repo-labels: [];
    in-out property <[string]> source-labels: [];
    in-out property <[string]> snapshot-ids: [];
    in-out property <[string]> snapshot-repo-names: [];
    // Config path for GUI state persistence.
    in-out property <string> active-config-path: "";
}
